from app.models.product import Product

# ── helpers ──────────────────────────────────────────────────────────────────
def p(id, name, price, orig, cat, gender, img, sizes, colors, desc, rating, reviews, is_new=False, is_sale=False):
    sale_price = int(orig * (1 - price / 100)) if isinstance(price, float) else price
    return Product(
        id=id, name=name, price=sale_price if isinstance(price, float) else price,
        original_price=orig, category=cat, gender=gender,
        image=img, images=[img],
        sizes=sizes, colors=colors, description=desc,
        rating=rating, reviews=reviews, is_new=is_new, is_sale=is_sale,
    )

S_UNISEX = ["XS","S","M","L","XL","XXL"]
S_SHIRT  = ["S","M","L","XL","XXL"]
S_JEANS  = ["28","29","30","31","32","34","36"]
S_DRESS  = ["XS","S","M","L"]
S_SHOE   = ["35","36","37","38","39","40","41","42"]

C_BASIC  = ["Trắng","Đen","Xám"]
C_EARTH  = ["Be","Nâu","Olive","Xanh rêu"]
C_VIVID  = ["Đỏ","Hồng","Xanh","Vàng"]
C_MONO   = ["Đen","Trắng"]
C_PASTEL = ["Hồng nhạt","Xanh nhạt","Tím nhạt","Vàng nhạt"]

IMG = {
    "ao_thun":   "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500&q=80",
    "ao_thun2":  "https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=500&q=80",
    "ao_thun3":  "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=500&q=80",
    "ao_so_mi":  "https://images.unsplash.com/photo-1594938298603-c8148c4b4357?w=500&q=80",
    "ao_so_mi2": "https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=500&q=80",
    "ao_khoac":  "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=500&q=80",
    "ao_khoac2": "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=500&q=80",
    "hoodie":    "https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=500&q=80",
    "hoodie2":   "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=500&q=80",
    "quan_jeans":"https://images.unsplash.com/photo-1542272604-787c3835535d?w=500&q=80",
    "quan_jeans2":"https://images.unsplash.com/photo-1555689502-c4b22d76c56f?w=500&q=80",
    "quan_short":"https://images.unsplash.com/photo-1591195853828-11db59a44f43?w=500&q=80",
    "quan_tay":  "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=500&q=80",
    "quan_jogger":"https://images.unsplash.com/photo-1552902865-b72c031ac5ea?w=500&q=80",
    "vay_hoa":   "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=500&q=80",
    "vay_maxi":  "https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=500&q=80",
    "vay_mini":  "https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=500&q=80",
    "vay_midi":  "https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=500&q=80",
    "dam_lien":  "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=500&q=80",
    "dam_maxi":  "https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=500&q=80",
    "dam_wrap":  "https://images.unsplash.com/photo-1612336307429-8a898d10e223?w=500&q=80",
    "ao_len":    "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=500&q=80",
    "ao_crop":   "https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=500&q=80",
    "ao_polo":   "https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?w=500&q=80",
    "ao_blazer": "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=500&q=80",
    "ao_vest":   "https://images.unsplash.com/photo-1594938298603-c8148c4b4357?w=500&q=80",
    "legging":   "https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=500&q=80",
    "quan_culottes":"https://images.unsplash.com/photo-1509631179647-0177331693ae?w=500&q=80",
    "set_bo":    "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=500&q=80",
    "jumpsuit":  "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=500&q=80",
}

PRODUCTS = [
    # ── ÁO THUN (1-18) ──────────────────────────────────────────────────────
    Product(id=1,  name="Áo Thun Basic Cotton Trắng", price=299000, original_price=299000, category="ao", gender="unisex", image=IMG["ao_thun"],  images=[IMG["ao_thun"]],  sizes=S_SHIRT,  colors=C_BASIC,  description="Áo thun basic cotton 100%, form regular, thoáng mát hàng ngày.", rating=4.5, reviews=312, is_new=False, is_sale=False),
    Product(id=2,  name="Áo Thun Oversize Unisex",    price=247000, original_price=399000, category="ao", gender="unisex", image=IMG["ao_thun2"], images=[IMG["ao_thun2"]], sizes=S_UNISEX, colors=["Đen","Trắng","Xám","Be"], description="Form oversize rộng rãi, chất cotton dày dặn, phong cách streetwear.", rating=4.7, reviews=528, is_new=True,  is_sale=True),
    Product(id=3,  name="Áo Thun In Hoạ Tiết",        price=1000, original_price=349000, category="ao", gender="unisex", image=IMG["ao_thun3"], images=[IMG["ao_thun3"]], sizes=S_SHIRT,  colors=["Trắng","Đen","Xanh navy"], description="Áo thun in hoạ tiết độc đáo, chất liệu cotton mềm mịn.", rating=4.3, reviews=187, is_new=False, is_sale=True),
    Product(id=4,  name="Áo Thun Polo Nam Classic",   price=399000, original_price=399000, category="ao", gender="nam",    image=IMG["ao_polo"],  images=[IMG["ao_polo"]],  sizes=S_SHIRT,  colors=["Trắng","Đen","Xanh navy","Đỏ"], description="Áo polo cổ bẻ, chất pique cotton cao cấp, lịch lãm.", rating=4.6, reviews=243, is_new=False, is_sale=False),
    Product(id=5,  name="Áo Thun Crop Top Nữ",        price=249000, original_price=299000, category="ao", gender="nu",     image=IMG["ao_crop"],  images=[IMG["ao_crop"]],  sizes=S_DRESS,  colors=C_PASTEL, description="Áo crop top ngắn, form ôm nhẹ, phù hợp mix đồ năng động.", rating=4.4, reviews=396, is_new=True,  is_sale=True),
    Product(id=6,  name="Áo Thun Tay Dài Slim Fit",   price=329000, original_price=329000, category="ao", gender="nam",    image=IMG["ao_thun"],  images=[IMG["ao_thun"]],  sizes=S_SHIRT,  colors=["Đen","Trắng","Xám đậm"], description="Áo thun tay dài form slim fit, giữ ấm nhẹ cho mùa thu.", rating=4.5, reviews=156, is_new=False, is_sale=False),
    Product(id=7,  name="Áo Thun Nữ Cổ V",            price=269000, original_price=319000, category="ao", gender="nu",     image=IMG["ao_thun2"], images=[IMG["ao_thun2"]], sizes=S_DRESS,  colors=["Trắng","Đen","Hồng","Xanh nhạt"], description="Áo thun cổ V nữ tính, chất cotton mềm, thoáng mát.", rating=4.4, reviews=289, is_new=False, is_sale=True),
    Product(id=8,  name="Áo Thun Graphic Streetwear", price=379000, original_price=449000, category="ao", gender="unisex", image=IMG["ao_thun3"], images=[IMG["ao_thun3"]], sizes=S_UNISEX, colors=["Đen","Trắng","Xám"], description="Áo thun graphic phong cách street, in hình độc đáo.", rating=4.6, reviews=412, is_new=True,  is_sale=True),
    Product(id=9,  name="Áo Len Cổ Lọ Nữ",            price=549000, original_price=649000, category="ao", gender="nu",     image=IMG["ao_len"],   images=[IMG["ao_len"]],   sizes=S_DRESS,  colors=["Be","Nâu","Trắng kem","Xám"], description="Áo len cổ lọ ấm áp, chất len mềm mịn, phong cách Hàn Quốc.", rating=4.8, reviews=334, is_new=True,  is_sale=True),
    Product(id=10, name="Áo Len Dệt Kim Oversize",     price=499000, original_price=499000, category="ao", gender="unisex", image=IMG["ao_len"],   images=[IMG["ao_len"]],   sizes=S_UNISEX, colors=["Be","Xám","Nâu đất"], description="Áo len dệt kim oversize ấm áp, phong cách vintage.", rating=4.7, reviews=267, is_new=False, is_sale=False),
    Product(id=11, name="Áo Sơ Mi Linen Nữ",           price=429000, original_price=429000, category="ao", gender="nu",     image=IMG["ao_so_mi"], images=[IMG["ao_so_mi"]], sizes=S_DRESS,  colors=["Trắng","Be","Xanh nhạt","Hồng nhạt"], description="Áo sơ mi linen thoáng mát, thanh lịch, phù hợp đi làm.", rating=4.5, reviews=198, is_new=False, is_sale=False),
    Product(id=12, name="Áo Sơ Mi Oxford Nam",          price=459000, original_price=549000, category="ao", gender="nam",    image=IMG["ao_so_mi2"],images=[IMG["ao_so_mi2"]],sizes=S_SHIRT,  colors=["Trắng","Xanh nhạt","Xám nhạt"], description="Áo sơ mi Oxford chất liệu cao cấp, form regular, lịch sự.", rating=4.6, reviews=321, is_new=False, is_sale=True),
    Product(id=13, name="Áo Sơ Mi Flannel Kẻ Caro",    price=489000, original_price=489000, category="ao", gender="unisex", image=IMG["ao_so_mi"], images=[IMG["ao_so_mi"]], sizes=S_UNISEX, colors=["Đỏ kẻ","Xanh kẻ","Đen kẻ"], description="Áo sơ mi flannel kẻ caro ấm áp, phong cách casual.", rating=4.4, reviews=145, is_new=False, is_sale=False),
    Product(id=14, name="Áo Blazer Nữ Công Sở",         price=899000, original_price=1099000,category="ao", gender="nu",     image=IMG["ao_blazer"],images=[IMG["ao_blazer"]],sizes=S_DRESS,  colors=["Đen","Be","Xám","Trắng kem"], description="Áo blazer nữ form fitted, chất liệu cao cấp, thanh lịch.", rating=4.8, reviews=276, is_new=True,  is_sale=True),
    Product(id=15, name="Áo Blazer Nam Slim Fit",        price=849000, original_price=999000, category="ao", gender="nam",    image=IMG["ao_blazer"],images=[IMG["ao_blazer"]],sizes=S_SHIRT,  colors=["Đen","Xám","Navy"], description="Áo blazer nam slim fit, chất vải cao cấp, phù hợp công sở.", rating=4.7, reviews=189, is_new=False, is_sale=True),
    Product(id=16, name="Áo Vest Nữ Thanh Lịch",        price=749000, original_price=749000, category="ao", gender="nu",     image=IMG["ao_vest"],  images=[IMG["ao_vest"]],  sizes=S_DRESS,  colors=["Đen","Trắng","Be"], description="Áo vest nữ không cổ, form ôm nhẹ, thanh lịch.", rating=4.6, reviews=134, is_new=False, is_sale=False),
    Product(id=17, name="Áo Hoodie Zip Unisex",          price=599000, original_price=699000, category="ao", gender="unisex", image=IMG["hoodie"],   images=[IMG["hoodie"]],   sizes=S_UNISEX, colors=["Đen","Xám","Trắng","Xanh navy"], description="Hoodie có khoá zip, chất nỉ bông dày, ấm áp mùa đông.", rating=4.7, reviews=445, is_new=False, is_sale=True),
    Product(id=18, name="Áo Hoodie Oversize Nữ",         price=549000, original_price=549000, category="ao", gender="nu",     image=IMG["hoodie2"],  images=[IMG["hoodie2"]],  sizes=S_UNISEX, colors=["Hồng","Tím nhạt","Be","Trắng"], description="Hoodie oversize nữ tính, chất nỉ mềm mịn, thoải mái.", rating=4.8, reviews=567, is_new=True,  is_sale=False),
]

PRODUCTS += [
    # ── ÁO KHOÁC (19-28) ────────────────────────────────────────────────────
    Product(id=19, name="Áo Khoác Bomber Unisex",      price=849000, original_price=1049000,category="ao", gender="unisex", image=IMG["ao_khoac"], images=[IMG["ao_khoac"]], sizes=S_UNISEX, colors=["Đen","Xanh navy","Olive","Nâu"], description="Áo khoác bomber phong cách streetwear, chất liệu dày dặn.", rating=4.6, reviews=378, is_new=False, is_sale=True),
    Product(id=20, name="Áo Khoác Denim Nam",           price=699000, original_price=699000, category="ao", gender="nam",    image=IMG["ao_khoac2"],images=[IMG["ao_khoac2"]],sizes=S_SHIRT,  colors=["Xanh đậm","Xanh nhạt","Đen"], description="Áo khoác denim cổ điển, bền đẹp, phong cách Mỹ.", rating=4.5, reviews=234, is_new=False, is_sale=False),
    Product(id=21, name="Áo Khoác Denim Nữ Crop",       price=649000, original_price=799000, category="ao", gender="nu",     image=IMG["ao_khoac2"],images=[IMG["ao_khoac2"]],sizes=S_DRESS,  colors=["Xanh nhạt","Trắng","Đen"], description="Áo khoác denim crop nữ, form ngắn cá tính.", rating=4.6, reviews=312, is_new=True,  is_sale=True),
    Product(id=22, name="Áo Khoác Gió Nhẹ Unisex",      price=599000, original_price=599000, category="ao", gender="unisex", image=IMG["ao_khoac"], images=[IMG["ao_khoac"]], sizes=S_UNISEX, colors=["Đen","Xanh navy","Xám","Đỏ"], description="Áo khoác gió nhẹ chống nước nhẹ, phù hợp thể thao.", rating=4.4, reviews=189, is_new=False, is_sale=False),
    Product(id=23, name="Áo Khoác Lông Cừu Nữ",         price=999000, original_price=1299000,category="ao", gender="nu",     image=IMG["ao_khoac"], images=[IMG["ao_khoac"]], sizes=S_DRESS,  colors=["Be","Trắng kem","Nâu nhạt"], description="Áo khoác lông cừu giả siêu ấm, phong cách Hàn Quốc.", rating=4.9, reviews=423, is_new=True,  is_sale=True),
    Product(id=24, name="Áo Khoác Varsity Unisex",       price=799000, original_price=799000, category="ao", gender="unisex", image=IMG["ao_khoac2"],images=[IMG["ao_khoac2"]],sizes=S_UNISEX, colors=["Đen trắng","Xanh trắng","Đỏ trắng"], description="Áo khoác varsity phong cách college Mỹ, cá tính.", rating=4.7, reviews=298, is_new=True,  is_sale=False),
    Product(id=25, name="Áo Khoác Blazer Nữ Tweed",      price=1199000,original_price=1499000,category="ao", gender="nu",     image=IMG["ao_blazer"],images=[IMG["ao_blazer"]],sizes=S_DRESS,  colors=["Be","Đen","Xám"], description="Áo khoác blazer tweed sang trọng, phong cách Pháp.", rating=4.8, reviews=167, is_new=False, is_sale=True),
    Product(id=26, name="Áo Khoác Puffer Nam",           price=1099000,original_price=1099000,category="ao", gender="nam",    image=IMG["ao_khoac"], images=[IMG["ao_khoac"]], sizes=S_SHIRT,  colors=["Đen","Xanh navy","Xám"], description="Áo khoác puffer giữ nhiệt tốt, nhẹ, phù hợp mùa đông.", rating=4.7, reviews=245, is_new=False, is_sale=False),
    Product(id=27, name="Áo Khoác Trench Coat Nữ",       price=1299000,original_price=1599000,category="ao", gender="nu",     image=IMG["ao_khoac2"],images=[IMG["ao_khoac2"]],sizes=S_DRESS,  colors=["Be","Đen","Nâu"], description="Trench coat nữ cổ điển, thanh lịch, phong cách Anh.", rating=4.9, reviews=312, is_new=True,  is_sale=True),
    Product(id=28, name="Áo Khoác Hoodie Zip Nữ",        price=649000, original_price=749000, category="ao", gender="nu",     image=IMG["hoodie2"],  images=[IMG["hoodie2"]],  sizes=S_UNISEX, colors=["Hồng","Tím","Xanh","Đen"], description="Hoodie zip nữ màu sắc tươi sáng, năng động.", rating=4.5, reviews=356, is_new=False, is_sale=True),
]

PRODUCTS += [
    # ── QUẦN (29-46) ─────────────────────────────────────────────────────────
    Product(id=29, name="Quần Jeans Slim Fit Nam",       price=599000, original_price=599000, category="quan", gender="nam",    image=IMG["quan_jeans"], images=[IMG["quan_jeans"]], sizes=S_JEANS, colors=["Xanh đậm","Xanh nhạt","Đen","Xám"], description="Quần jeans slim fit dáng ôm vừa, chất denim cao cấp.", rating=4.7, reviews=489, is_new=True,  is_sale=False),
    Product(id=30, name="Quần Jeans Skinny Nữ",          price=549000, original_price=649000, category="quan", gender="nu",     image=IMG["quan_jeans2"],images=[IMG["quan_jeans2"]],sizes=S_JEANS, colors=["Xanh đậm","Đen","Xanh rách"], description="Quần jeans skinny ôm sát, tôn dáng, phong cách trẻ trung.", rating=4.6, reviews=567, is_new=False, is_sale=True),
    Product(id=31, name="Quần Jeans Straight Unisex",    price=629000, original_price=629000, category="quan", gender="unisex", image=IMG["quan_jeans"], images=[IMG["quan_jeans"]], sizes=S_JEANS, colors=["Xanh đậm","Xanh nhạt","Đen"], description="Quần jeans straight leg cổ điển, phù hợp mọi vóc dáng.", rating=4.5, reviews=334, is_new=False, is_sale=False),
    Product(id=32, name="Quần Jeans Wide Leg Nữ",        price=679000, original_price=799000, category="quan", gender="nu",     image=IMG["quan_jeans2"],images=[IMG["quan_jeans2"]],sizes=S_JEANS, colors=["Xanh nhạt","Trắng","Đen"], description="Quần jeans ống rộng thời thượng, tôn dáng cao.", rating=4.8, reviews=423, is_new=True,  is_sale=True),
    Product(id=33, name="Quần Short Kaki Nam",            price=329000, original_price=329000, category="quan", gender="nam",    image=IMG["quan_short"], images=[IMG["quan_short"]], sizes=["28","30","32","34"], colors=C_EARTH, description="Quần short kaki năng động, thoải mái mùa hè.", rating=4.3, reviews=267, is_new=False, is_sale=False),
    Product(id=34, name="Quần Short Denim Nữ",            price=349000, original_price=429000, category="quan", gender="nu",     image=IMG["quan_short"], images=[IMG["quan_short"]], sizes=S_DRESS,  colors=["Xanh nhạt","Trắng","Đen"], description="Quần short denim nữ cá tính, phù hợp mùa hè.", rating=4.5, reviews=389, is_new=False, is_sale=True),
    Product(id=35, name="Quần Tây Ống Suông Nam",         price=599000, original_price=699000, category="quan", gender="nam",    image=IMG["quan_tay"],   images=[IMG["quan_tay"]],   sizes=S_JEANS, colors=["Đen","Xám","Navy","Be"], description="Quần tây ống suông lịch lãm, phù hợp công sở.", rating=4.6, reviews=198, is_new=False, is_sale=True),
    Product(id=36, name="Quần Tây Nữ Ống Rộng",          price=579000, original_price=579000, category="quan", gender="nu",     image=IMG["quan_tay"],   images=[IMG["quan_tay"]],   sizes=S_DRESS,  colors=["Đen","Trắng","Be","Xám"], description="Quần tây nữ ống rộng thanh lịch, phù hợp công sở.", rating=4.7, reviews=312, is_new=True,  is_sale=False),
    Product(id=37, name="Quần Jogger Unisex",             price=449000, original_price=449000, category="quan", gender="unisex", image=IMG["quan_jogger"],images=[IMG["quan_jogger"]],sizes=S_UNISEX, colors=["Đen","Xám","Be","Xanh navy"], description="Quần jogger thoải mái, phù hợp thể thao và casual.", rating=4.5, reviews=445, is_new=False, is_sale=False),
    Product(id=38, name="Quần Jogger Nữ Pastel",          price=429000, original_price=499000, category="quan", gender="nu",     image=IMG["quan_jogger"],images=[IMG["quan_jogger"]],sizes=S_UNISEX, colors=C_PASTEL, description="Quần jogger nữ màu pastel dễ thương, thoải mái.", rating=4.6, reviews=378, is_new=True,  is_sale=True),
    Product(id=39, name="Quần Legging Nữ Cạp Cao",        price=299000, original_price=349000, category="quan", gender="nu",     image=IMG["legging"],    images=[IMG["legging"]],    sizes=S_DRESS,  colors=["Đen","Xám","Navy"], description="Quần legging cạp cao tôn dáng, chất liệu co giãn 4 chiều.", rating=4.7, reviews=623, is_new=False, is_sale=True),
    Product(id=40, name="Quần Legging Thể Thao",          price=349000, original_price=349000, category="quan", gender="nu",     image=IMG["legging"],    images=[IMG["legging"]],    sizes=S_DRESS,  colors=["Đen","Xanh","Hồng","Tím"], description="Quần legging thể thao chất liệu thấm hút mồ hôi.", rating=4.6, reviews=445, is_new=False, is_sale=False),
    Product(id=41, name="Quần Culottes Nữ",               price=499000, original_price=599000, category="quan", gender="nu",     image=IMG["quan_culottes"],images=[IMG["quan_culottes"]],sizes=S_DRESS,colors=["Đen","Be","Xám","Trắng"], description="Quần culottes ống loe nữ tính, thanh lịch.", rating=4.5, reviews=234, is_new=False, is_sale=True),
    Product(id=42, name="Quần Short Thể Thao Nam",         price=279000, original_price=279000, category="quan", gender="nam",    image=IMG["quan_short"], images=[IMG["quan_short"]], sizes=S_SHIRT,  colors=["Đen","Xám","Xanh navy","Đỏ"], description="Quần short thể thao thoáng khí, phù hợp tập gym.", rating=4.4, reviews=312, is_new=False, is_sale=False),
    Product(id=43, name="Quần Jeans Baggy Unisex",         price=699000, original_price=849000, category="quan", gender="unisex", image=IMG["quan_jeans"], images=[IMG["quan_jeans"]], sizes=S_JEANS, colors=["Xanh nhạt","Xanh đậm","Đen"], description="Quần jeans baggy phong cách Y2K, cá tính.", rating=4.7, reviews=389, is_new=True,  is_sale=True),
    Product(id=44, name="Quần Tây Kẻ Sọc Nam",            price=649000, original_price=649000, category="quan", gender="nam",    image=IMG["quan_tay"],   images=[IMG["quan_tay"]],   sizes=S_JEANS, colors=["Đen trắng","Xám trắng","Navy trắng"], description="Quần tây kẻ sọc lịch lãm, phù hợp công sở.", rating=4.5, reviews=167, is_new=False, is_sale=False),
    Product(id=45, name="Quần Short Linen Nữ",             price=379000, original_price=449000, category="quan", gender="nu",     image=IMG["quan_short"], images=[IMG["quan_short"]], sizes=S_DRESS,  colors=["Trắng","Be","Xanh nhạt"], description="Quần short linen thoáng mát, phù hợp mùa hè.", rating=4.4, reviews=198, is_new=False, is_sale=True),
    Product(id=46, name="Quần Jeans Mom Fit Nữ",           price=629000, original_price=629000, category="quan", gender="nu",     image=IMG["quan_jeans2"],images=[IMG["quan_jeans2"]],sizes=S_JEANS, colors=["Xanh nhạt","Trắng","Đen"], description="Quần jeans mom fit cạp cao, phong cách retro.", rating=4.6, reviews=445, is_new=True,  is_sale=False),
]

PRODUCTS += [
    # ── VÁY & ĐẦM (47-68) ───────────────────────────────────────────────────
    Product(id=47, name="Váy Hoa Nhí Dáng Xòe",         price=449000, original_price=549000, category="vay", gender="nu", image=IMG["vay_hoa"],  images=[IMG["vay_hoa"]],  sizes=S_DRESS, colors=["Hồng","Xanh","Vàng","Trắng"], description="Váy hoa nhí dáng xòe nhẹ nhàng, nữ tính.", rating=4.8, reviews=534, is_new=True,  is_sale=True),
    Product(id=48, name="Váy Maxi Boho Dài",             price=679000, original_price=779000, category="vay", gender="nu", image=IMG["vay_maxi"], images=[IMG["vay_maxi"]], sizes=S_DRESS, colors=["Trắng","Nâu","Đỏ đô","Be"], description="Váy maxi boho phong cách tự do, nhẹ nhàng.", rating=4.9, reviews=423, is_new=True,  is_sale=True),
    Product(id=49, name="Váy Mini Denim Cá Tính",        price=399000, original_price=399000, category="vay", gender="nu", image=IMG["vay_mini"], images=[IMG["vay_mini"]], sizes=S_DRESS, colors=["Xanh nhạt","Đen","Trắng"], description="Váy mini denim cá tính, phong cách trẻ trung.", rating=4.5, reviews=312, is_new=False, is_sale=False),
    Product(id=50, name="Váy Midi Xếp Ly Thanh Lịch",   price=549000, original_price=649000, category="vay", gender="nu", image=IMG["vay_midi"], images=[IMG["vay_midi"]], sizes=S_DRESS, colors=["Đen","Be","Xám","Trắng kem"], description="Váy midi xếp ly thanh lịch, phù hợp công sở.", rating=4.7, reviews=267, is_new=False, is_sale=True),
    Product(id=51, name="Váy Wrap Floral Nữ Tính",       price=499000, original_price=499000, category="vay", gender="nu", image=IMG["vay_hoa"],  images=[IMG["vay_hoa"]],  sizes=S_DRESS, colors=["Hồng hoa","Xanh hoa","Vàng hoa"], description="Váy wrap hoa nữ tính, dễ mặc, phù hợp đi chơi.", rating=4.6, reviews=389, is_new=False, is_sale=False),
    Product(id=52, name="Váy Chữ A Công Sở",             price=599000, original_price=699000, category="vay", gender="nu", image=IMG["vay_midi"], images=[IMG["vay_midi"]], sizes=S_DRESS, colors=["Đen","Navy","Xám","Be"], description="Váy chữ A thanh lịch, phù hợp môi trường công sở.", rating=4.7, reviews=198, is_new=False, is_sale=True),
    Product(id=53, name="Váy Ren Trắng Dự Tiệc",         price=799000, original_price=999000, category="vay", gender="nu", image=IMG["vay_mini"], images=[IMG["vay_mini"]], sizes=S_DRESS, colors=["Trắng","Kem","Hồng nhạt"], description="Váy ren trắng sang trọng, phù hợp dự tiệc.", rating=4.8, reviews=156, is_new=True,  is_sale=True),
    Product(id=54, name="Váy Thun Ôm Body Nữ",           price=299000, original_price=299000, category="vay", gender="nu", image=IMG["vay_mini"], images=[IMG["vay_mini"]], sizes=S_DRESS, colors=["Đen","Trắng","Be","Hồng"], description="Váy thun ôm body tôn dáng, chất liệu co giãn.", rating=4.4, reviews=445, is_new=False, is_sale=False),
    Product(id=55, name="Đầm Liền Thân Hoa Nhí",         price=549000, original_price=649000, category="vay", gender="nu", image=IMG["dam_lien"], images=[IMG["dam_lien"]], sizes=S_DRESS, colors=["Hồng hoa","Xanh hoa","Trắng hoa"], description="Đầm liền thân hoa nhí dễ thương, phù hợp đi chơi.", rating=4.7, reviews=378, is_new=True,  is_sale=True),
    Product(id=56, name="Đầm Maxi Cổ Yếm Nữ",           price=699000, original_price=699000, category="vay", gender="nu", image=IMG["dam_maxi"], images=[IMG["dam_maxi"]], sizes=S_DRESS, colors=["Trắng","Be","Xanh nhạt"], description="Đầm maxi cổ yếm thanh lịch, phù hợp đi biển.", rating=4.8, reviews=312, is_new=False, is_sale=False),
    Product(id=57, name="Đầm Wrap Midi Thanh Lịch",      price=649000, original_price=799000, category="vay", gender="nu", image=IMG["dam_wrap"], images=[IMG["dam_wrap"]], sizes=S_DRESS, colors=["Đen","Đỏ đô","Xanh navy"], description="Đầm wrap midi thanh lịch, phù hợp công sở và dự tiệc.", rating=4.7, reviews=234, is_new=False, is_sale=True),
    Product(id=58, name="Đầm Babydoll Nữ Tính",          price=499000, original_price=599000, category="vay", gender="nu", image=IMG["dam_lien"], images=[IMG["dam_lien"]], sizes=S_DRESS, colors=["Trắng","Hồng","Xanh nhạt","Vàng nhạt"], description="Đầm babydoll nữ tính, nhẹ nhàng, phù hợp đi chơi.", rating=4.6, reviews=289, is_new=True,  is_sale=True),
    Product(id=59, name="Đầm Dự Tiệc Sequin",            price=1299000,original_price=1599000,category="vay", gender="nu", image=IMG["dam_maxi"], images=[IMG["dam_maxi"]], sizes=S_DRESS, colors=["Vàng","Bạc","Đen"], description="Đầm sequin lấp lánh, sang trọng cho các buổi tiệc.", rating=4.9, reviews=167, is_new=True,  is_sale=True),
    Product(id=60, name="Đầm Sơ Mi Dài Nữ",              price=579000, original_price=579000, category="vay", gender="nu", image=IMG["dam_wrap"], images=[IMG["dam_wrap"]], sizes=S_DRESS, colors=["Trắng","Be","Xanh nhạt","Kẻ sọc"], description="Đầm sơ mi dài phong cách casual chic.", rating=4.5, reviews=198, is_new=False, is_sale=False),
    Product(id=61, name="Jumpsuit Nữ Cổ Yếm",            price=699000, original_price=849000, category="vay", gender="nu", image=IMG["jumpsuit"], images=[IMG["jumpsuit"]], sizes=S_DRESS, colors=["Đen","Trắng","Be","Xanh navy"], description="Jumpsuit cổ yếm thanh lịch, tiện lợi.", rating=4.7, reviews=312, is_new=True,  is_sale=True),
    Product(id=62, name="Jumpsuit Thể Thao Nữ",           price=599000, original_price=599000, category="vay", gender="nu", image=IMG["jumpsuit"], images=[IMG["jumpsuit"]], sizes=S_DRESS, colors=["Đen","Xám","Xanh navy"], description="Jumpsuit thể thao năng động, thoải mái.", rating=4.5, reviews=189, is_new=False, is_sale=False),
    Product(id=63, name="Váy Pleated Midi Hàn Quốc",     price=529000, original_price=629000, category="vay", gender="nu", image=IMG["vay_midi"], images=[IMG["vay_midi"]], sizes=S_DRESS, colors=["Đen","Be","Hồng nhạt","Xanh nhạt"], description="Váy pleated midi phong cách Hàn Quốc, thanh lịch.", rating=4.8, reviews=445, is_new=True,  is_sale=True),
    Product(id=64, name="Váy Tennis Thể Thao",            price=449000, original_price=449000, category="vay", gender="nu", image=IMG["vay_mini"], images=[IMG["vay_mini"]], sizes=S_DRESS, colors=["Trắng","Đen","Hồng","Xanh"], description="Váy tennis năng động, phù hợp thể thao và casual.", rating=4.6, reviews=267, is_new=False, is_sale=False),
    Product(id=65, name="Đầm Cổ Vuông Vintage",           price=599000, original_price=699000, category="vay", gender="nu", image=IMG["dam_lien"], images=[IMG["dam_lien"]], sizes=S_DRESS, colors=["Đen","Trắng","Đỏ","Xanh"], description="Đầm cổ vuông phong cách vintage, nữ tính.", rating=4.7, reviews=334, is_new=False, is_sale=True),
    Product(id=66, name="Váy Chân Xếp Ly Thun Xốp",      price=449000, original_price=449000, category="vay", gender="nu", image=IMG["vay_midi"], images=[IMG["vay_midi"]], sizes=S_DRESS, colors=["Đen","Xám","Xanh đen","Nâu"], description="Váy chân xếp ly vải thun xốp, thoải mái.", rating=4.5, reviews=378, is_new=False, is_sale=False),
    Product(id=67, name="Đầm Linen Mùa Hè",              price=649000, original_price=799000, category="vay", gender="nu", image=IMG["dam_maxi"], images=[IMG["dam_maxi"]], sizes=S_DRESS, colors=["Trắng","Be","Xanh nhạt","Vàng nhạt"], description="Đầm linen thoáng mát, phù hợp mùa hè.", rating=4.7, reviews=223, is_new=True,  is_sale=True),
    Product(id=68, name="Váy Satin Dự Tiệc",              price=899000, original_price=1099000,category="vay", gender="nu", image=IMG["dam_lien"], images=[IMG["dam_lien"]], sizes=S_DRESS, colors=["Đen","Đỏ đô","Xanh navy","Vàng đồng"], description="Váy satin sang trọng, phù hợp dự tiệc tối.", rating=4.8, reviews=145, is_new=True,  is_sale=True),
]

PRODUCTS += [
    # ── SET BỘ (69-78) ───────────────────────────────────────────────────────
    Product(id=69, name="Set Bộ Áo Quần Thể Thao",      price=699000, original_price=849000, category="ao", gender="nu",     image=IMG["set_bo"],   images=[IMG["set_bo"]],   sizes=S_DRESS,  colors=["Đen","Xám","Hồng","Xanh"], description="Set bộ áo quần thể thao đồng bộ, thoải mái.", rating=4.7, reviews=389, is_new=True,  is_sale=True),
    Product(id=70, name="Set Bộ Linen Mùa Hè Nữ",       price=799000, original_price=799000, category="ao", gender="nu",     image=IMG["set_bo"],   images=[IMG["set_bo"]],   sizes=S_DRESS,  colors=["Trắng","Be","Xanh nhạt"], description="Set bộ linen áo + quần thoáng mát mùa hè.", rating=4.8, reviews=267, is_new=True,  is_sale=False),
    Product(id=71, name="Set Bộ Hoodie + Jogger",        price=899000, original_price=1099000,category="ao", gender="unisex", image=IMG["hoodie"],   images=[IMG["hoodie"]],   sizes=S_UNISEX, colors=["Đen","Xám","Be","Hồng"], description="Set bộ hoodie + jogger đồng bộ, thoải mái.", rating=4.7, reviews=445, is_new=False, is_sale=True),
    Product(id=72, name="Set Bộ Blazer + Quần Tây Nữ",  price=1499000,original_price=1799000,category="ao", gender="nu",     image=IMG["ao_blazer"],images=[IMG["ao_blazer"]],sizes=S_DRESS,  colors=["Đen","Be","Xám"], description="Set bộ blazer + quần tây thanh lịch, phù hợp công sở.", rating=4.9, reviews=198, is_new=True,  is_sale=True),
    Product(id=73, name="Set Bộ Áo Crop + Chân Váy",    price=699000, original_price=699000, category="ao", gender="nu",     image=IMG["set_bo"],   images=[IMG["set_bo"]],   sizes=S_DRESS,  colors=["Trắng","Đen","Hồng","Be"], description="Set bộ áo crop + chân váy midi đồng bộ.", rating=4.6, reviews=312, is_new=False, is_sale=False),
    Product(id=74, name="Set Bộ Thể Thao Nam",           price=749000, original_price=899000, category="ao", gender="nam",    image=IMG["set_bo"],   images=[IMG["set_bo"]],   sizes=S_SHIRT,  colors=["Đen","Xám","Xanh navy"], description="Set bộ áo + quần thể thao nam đồng bộ.", rating=4.5, reviews=234, is_new=False, is_sale=True),
    Product(id=75, name="Set Bộ Pyjama Nữ",              price=499000, original_price=499000, category="ao", gender="nu",     image=IMG["set_bo"],   images=[IMG["set_bo"]],   sizes=S_DRESS,  colors=["Hồng kẻ","Xanh kẻ","Vàng kẻ"], description="Set bộ pyjama mềm mịn, thoải mái khi ngủ.", rating=4.7, reviews=356, is_new=False, is_sale=False),
    Product(id=76, name="Set Bộ Len Mùa Đông Nữ",        price=999000, original_price=1199000,category="ao", gender="nu",     image=IMG["ao_len"],   images=[IMG["ao_len"]],   sizes=S_DRESS,  colors=["Be","Nâu","Xám","Trắng kem"], description="Set bộ áo len + quần len ấm áp mùa đông.", rating=4.8, reviews=178, is_new=True,  is_sale=True),
    Product(id=77, name="Set Bộ Sơ Mi + Quần Short",     price=799000, original_price=799000, category="ao", gender="unisex", image=IMG["ao_so_mi"], images=[IMG["ao_so_mi"]], sizes=S_UNISEX, colors=["Trắng","Be","Xanh nhạt"], description="Set bộ sơ mi + quần short đồng bộ, phù hợp đi chơi.", rating=4.5, reviews=189, is_new=False, is_sale=False),
    Product(id=78, name="Set Bộ Denim Jacket + Jeans",   price=1199000,original_price=1399000,category="ao", gender="unisex", image=IMG["ao_khoac2"],images=[IMG["ao_khoac2"]],sizes=S_UNISEX, colors=["Xanh nhạt","Xanh đậm","Đen"], description="Set bộ denim jacket + jeans đồng bộ, phong cách.", rating=4.7, reviews=267, is_new=True,  is_sale=True),
]

PRODUCTS += [
    # ── GIÀY (79-90) ─────────────────────────────────────────────────────────
    Product(id=79, name="Giày Sneaker Trắng Unisex",     price=799000, original_price=999000, category="giay", gender="unisex", image="https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&q=80", images=["https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&q=80"], sizes=S_SHOE, colors=["Trắng","Đen","Xám"], description="Giày sneaker trắng cổ điển, phù hợp mọi outfit.", rating=4.7, reviews=567, is_new=False, is_sale=True),
    Product(id=80, name="Giày Cao Gót Mũi Nhọn Nữ",     price=549000, original_price=649000, category="giay", gender="nu",     image="https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=500&q=80", images=["https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=500&q=80"], sizes=["35","36","37","38","39"], colors=["Đen","Nude","Đỏ","Trắng"], description="Giày cao gót mũi nhọn thanh lịch, tôn dáng.", rating=4.6, reviews=389, is_new=True,  is_sale=True),
    Product(id=81, name="Giày Sandal Quai Mảnh Nữ",      price=449000, original_price=449000, category="giay", gender="nu",     image="https://images.unsplash.com/photo-1603487742131-4160ec999306?w=500&q=80", images=["https://images.unsplash.com/photo-1603487742131-4160ec999306?w=500&q=80"], sizes=["35","36","37","38","39"], colors=["Vàng","Bạc","Đen","Trắng"], description="Giày sandal quai mảnh thanh lịch, phù hợp mùa hè.", rating=4.5, reviews=312, is_new=False, is_sale=False),
    Product(id=82, name="Giày Búp Bê Nữ Classic",        price=399000, original_price=499000, category="giay", gender="nu",     image="https://images.unsplash.com/photo-1518049362265-d5b2a6467637?w=500&q=80", images=["https://images.unsplash.com/photo-1518049362265-d5b2a6467637?w=500&q=80"], sizes=["35","36","37","38","39"], colors=["Đen","Nude","Trắng","Hồng"], description="Giày búp bê cổ điển, thoải mái, phù hợp đi làm.", rating=4.6, reviews=445, is_new=False, is_sale=True),
    Product(id=83, name="Giày Loafer Da Nam",             price=899000, original_price=899000, category="giay", gender="nam",    image="https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=500&q=80", images=["https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=500&q=80"], sizes=["39","40","41","42","43"], colors=["Đen","Nâu","Tan"], description="Giày loafer da thật, lịch lãm, phù hợp công sở.", rating=4.8, reviews=234, is_new=False, is_sale=False),
    Product(id=84, name="Giày Boot Cổ Cao Nữ",           price=1199000,original_price=1499000,category="giay", gender="nu",     image="https://images.unsplash.com/photo-1608256246200-53e635b5b65f?w=500&q=80", images=["https://images.unsplash.com/photo-1608256246200-53e635b5b65f?w=500&q=80"], sizes=["35","36","37","38","39"], colors=["Đen","Nâu","Trắng"], description="Giày boot cổ cao thời trang, phù hợp mùa đông.", rating=4.7, reviews=189, is_new=True,  is_sale=True),
    Product(id=85, name="Giày Thể Thao Chạy Bộ",         price=999000, original_price=1199000,category="giay", gender="unisex", image="https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&q=80", images=["https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&q=80"], sizes=S_SHOE, colors=["Trắng","Đen","Xanh","Đỏ"], description="Giày thể thao chạy bộ đế êm, hỗ trợ tốt.", rating=4.7, reviews=378, is_new=False, is_sale=True),
    Product(id=86, name="Dép Sandal Đế Bằng Nữ",         price=299000, original_price=299000, category="giay", gender="nu",     image="https://images.unsplash.com/photo-1603487742131-4160ec999306?w=500&q=80", images=["https://images.unsplash.com/photo-1603487742131-4160ec999306?w=500&q=80"], sizes=["35","36","37","38","39"], colors=["Trắng","Đen","Be","Hồng"], description="Dép sandal đế bằng thoải mái, phù hợp đi biển.", rating=4.4, reviews=445, is_new=False, is_sale=False),
    Product(id=87, name="Giày Oxford Nam Cổ Điển",        price=849000, original_price=999000, category="giay", gender="nam",    image="https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=500&q=80", images=["https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=500&q=80"], sizes=["39","40","41","42","43"], colors=["Đen","Nâu"], description="Giày oxford da thật cổ điển, lịch lãm.", rating=4.7, reviews=198, is_new=False, is_sale=True),
    Product(id=88, name="Giày Mule Nữ Thời Trang",        price=499000, original_price=599000, category="giay", gender="nu",     image="https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=500&q=80", images=["https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=500&q=80"], sizes=["35","36","37","38","39"], colors=["Đen","Be","Trắng","Hồng"], description="Giày mule thời trang, dễ mang, phù hợp đi chơi.", rating=4.5, reviews=267, is_new=True,  is_sale=True),
    Product(id=89, name="Giày Sneaker Platform Nữ",       price=899000, original_price=899000, category="giay", gender="nu",     image="https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&q=80", images=["https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&q=80"], sizes=["35","36","37","38","39"], colors=["Trắng","Đen","Hồng"], description="Giày sneaker platform tăng chiều cao, thời trang.", rating=4.6, reviews=334, is_new=True,  is_sale=False),
    Product(id=90, name="Giày Cao Gót Block Heel",        price=649000, original_price=799000, category="giay", gender="nu",     image="https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=500&q=80", images=["https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=500&q=80"], sizes=["35","36","37","38","39"], colors=["Đen","Nude","Đỏ","Trắng"], description="Giày cao gót block heel vững chắc, thoải mái.", rating=4.7, reviews=289, is_new=False, is_sale=True),
]

PRODUCTS += [
    # ── TÚI XÁCH (91-100) ────────────────────────────────────────────────────
    Product(id=91,  name="Túi Tote Canvas Unisex",        price=349000, original_price=349000, category="tui", gender="unisex", image="https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=500&q=80", images=["https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=500&q=80"], sizes=["One Size"], colors=["Trắng","Đen","Be","Xanh navy"], description="Túi tote canvas đơn giản, tiện dụng hàng ngày.", rating=4.5, reviews=445, is_new=False, is_sale=False),
    Product(id=92,  name="Túi Xách Nhỏ Bucket Bag",       price=799000, original_price=999000, category="tui", gender="nu",     image="https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=500&q=80", images=["https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=500&q=80"], sizes=["One Size"], colors=["Đen","Be","Nâu","Hồng"], description="Túi bucket bag nhỏ xinh, phù hợp đi chơi.", rating=4.7, reviews=312, is_new=True,  is_sale=True),
    Product(id=93,  name="Túi Đeo Chéo Mini Nữ",          price=499000, original_price=599000, category="tui", gender="nu",     image="https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=500&q=80", images=["https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=500&q=80"], sizes=["One Size"], colors=["Đen","Trắng","Hồng","Be"], description="Túi đeo chéo mini tiện lợi, phù hợp đi chơi.", rating=4.6, reviews=389, is_new=False, is_sale=True),
    Product(id=94,  name="Túi Clutch Dự Tiệc",            price=599000, original_price=599000, category="tui", gender="nu",     image="https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=500&q=80", images=["https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=500&q=80"], sizes=["One Size"], colors=["Vàng","Bạc","Đen","Đỏ"], description="Túi clutch sang trọng, phù hợp dự tiệc.", rating=4.8, reviews=167, is_new=True,  is_sale=False),
    Product(id=95,  name="Balo Da Thời Trang",             price=999000, original_price=1199000,category="tui", gender="unisex", image="https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=500&q=80", images=["https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=500&q=80"], sizes=["One Size"], colors=["Đen","Nâu","Be"], description="Balo da thời trang, nhiều ngăn tiện dụng.", rating=4.7, reviews=234, is_new=False, is_sale=True),
    Product(id=96,  name="Túi Xách Lớn Tote Da",          price=1299000,original_price=1299000,category="tui", gender="nu",     image="https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=500&q=80", images=["https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=500&q=80"], sizes=["One Size"], colors=["Đen","Be","Nâu","Trắng"], description="Túi tote da lớn, đựng được nhiều đồ, phù hợp đi làm.", rating=4.8, reviews=198, is_new=True,  is_sale=False),
    Product(id=97,  name="Túi Xách Vai Nữ Thời Trang",    price=749000, original_price=899000, category="tui", gender="nu",     image="https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=500&q=80", images=["https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=500&q=80"], sizes=["One Size"], colors=["Đen","Be","Hồng","Xanh"], description="Túi xách vai thời trang, phù hợp nhiều dịp.", rating=4.6, reviews=312, is_new=False, is_sale=True),
    Product(id=98,  name="Ví Da Nữ Dài",                  price=399000, original_price=499000, category="tui", gender="nu",     image="https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=500&q=80", images=["https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=500&q=80"], sizes=["One Size"], colors=["Đen","Nâu","Đỏ","Be"], description="Ví da nữ dài nhiều ngăn, tiện dụng.", rating=4.5, reviews=267, is_new=False, is_sale=True),
    Product(id=99,  name="Túi Xách Nhỏ Chain Bag",        price=899000, original_price=1099000,category="tui", gender="nu",     image="https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=500&q=80", images=["https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=500&q=80"], sizes=["One Size"], colors=["Đen","Vàng","Bạc","Hồng"], description="Túi chain bag sang trọng, phù hợp dự tiệc và đi chơi.", rating=4.8, reviews=189, is_new=True,  is_sale=True),
    Product(id=100, name="Balo Thể Thao Unisex",           price=599000, original_price=599000, category="tui", gender="unisex", image="https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=500&q=80", images=["https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=500&q=80"], sizes=["One Size"], colors=["Đen","Xám","Xanh navy","Đỏ"], description="Balo thể thao chống nước, nhiều ngăn tiện dụng.", rating=4.6, reviews=356, is_new=False, is_sale=False),
]
